-- Tabela para guardar os perfis dos usuários (Clientes)
-- Esta tabela estende a tabela 'auth.users'
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  full_name text,
  cpf text,
  phone text,
  primary key (id)
);

-- Tabela para os Produtos da loja
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10, 2) not null,
  created_at timestamptz default now()
);

-- Tabela para os Pedidos
create table public.orders (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.profiles,
  status text default 'pending',
  total_amount numeric(10, 2) default 0,
  created_at timestamptz default now()
);

-- Tabela de junção para os Itens de um Pedido
-- Conecta a tabela 'orders' com a tabela 'products'
create table public.order_items (
  order_id bigint not null references public.orders,
  product_id bigint not null references public.products,
  quantity int not null,
  primary key (order_id, product_id)
);